<?php
/**
 * @file
 * install file for epsacrop.module
 */


/**
 * Implements hook_schema().
 *
 * @access public
 * @return array
 */
function epsacrop_schema() {
  $schema['epsacrop_files'] = array(
    'description' => 'TODO: please describe this table!',
    'fields' => array(
      'fid' => array(
        'description' => 'TODO: please describe this field!',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'coords' => array(
        'description' => 'TODO: please describe this field!',
        'type' => 'text',
        'size' => 'big',
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('fid'),
  );
  return $schema;
}

/**
 * Implements hook_install().
 *
 * @access public
 * @return void
 */
function epsacrop_install() {
  db_update('system')
    ->fields(array('weight' => 10))
    ->condition('name', 'epsacrop')
    ->execute();
}

/**
 * Implements hook_uninstall().
 *
 * @access public
 * @return void
 */
function epsacrop_uninstall() { }

/**
 * Implements hook_update_last_removed().
 */
function modulename_update_last_removed() {
  return 7202;
}
